### ISSUE TITLE
Potential Command

### ISSUE THREAD

**Issue by Lifelessyeti40** [ValAlpha/TemplateBot#2]
Could we possibly add a "Rock, Paper Scissors command". I think this would be a great community activity to play

**Comment by ValAlpha** [comment]
Good idea ⭐

**Comment by Lifelessyeti40** [comment]
> Good idea ⭐

Thank you for the quick response 

Much appreciated :)

**Comment by Elara-Discord-Bots** [comment]
boop

**Comment by ValAlpha** [comment]
![image](https://user-images.githubusercontent.com/38390851/111241374-dd861b00-85f4-11eb-8b5b-c9b19442339a.png)

https://github.com/ValAlpha/TemplateBot/blob/main/commands/fun/rps.js

Thank you for the idea :)

**Comment by ValAlpha** [comment]
🗿📄✂🦎🖖 - If you now you know.
